version: '3.8'

services:
  parking-app:
    container_name: parking-getaway
    build:
      context: .
      dockerfile: ./apps/parking-app/DockerFile
      target: developement
    command: npm run start:dev parking-dev
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'

  users:
    container_name: parking-users
    build:
      context: .
      dockerfile: ./apps/users/DockerFile
      target: developement
    command: npm run start:dev users
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules


  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'

  postgres:
    container_name: parking-db
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
       - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
    postgres:
      name: p-backend
